// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using ScheduleClin.Context;

#nullable disable

namespace ScheduleClin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623230000_AddAudit")]
    partial class AddAudit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScheduleClin.Models.Audit.Audit", b =>
                {
                    b.Property<Guid>("AuditId").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp").HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId").HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName").HasColumnType("nvarchar(max)");

                    b.Property<string>("Action").HasColumnType("nvarchar(max)");

                    b.Property<string>("Path").HasColumnType("nvarchar(max)");

                    b.Property<string>("Method").HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode").HasColumnType("int");

                    b.Property<string>("Details").HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Audits");
                });
#pragma warning restore 612, 618
        }
    }
}
